### ISSUE TITLE
Preserve File Permissions (as in GNU tar)

### ISSUE THREAD

**Issue by b-ramsey** [alexcrichton/tar-rs#74]
While creating the tar archive not all of the permissions set on the files being appended to the archive are being preserved. Specifically, if the set-user-ID permission bit is set to 1 then this library will disable this bit.

In the GNU tar program, all of the file permissions are being preserved during creation of the archive.

**Comment by alexcrichton** [comment]
Aha, certainly! I believe [this is where it'd go](https://github.com/alexcrichton/tar-rs/blob/master/src/entry.rs#L329-L337), I'm just not entirely sure how...

**Comment by b-ramsey** [comment]
Actually, I believe it is from [this](https://github.com/alexcrichton/tar-rs/blob/master/src/header.rs#L385). Where the mode is being bitwise-& with the octal number 3777. 

This enforces the removal of the setuid bit but keeps the setgid and sticky-bit

**Comment by alexcrichton** [comment]
Ah that'd do it, perhaps we should call `chmod` directly?

**Comment by alexcrichton** [comment]
(that'd work, right?)

**Comment by b-ramsey** [comment]
Well its how I solved a similar issue in my own code. The main issue is that with Rust you are able to obtain the special permission bits (with st_mode()) but not set the mode without resorting to using libc::chmod.

It should also be noted that the mode is modified as described above in two locations in the header.rs file, in the set_mode function & in the fill_from function.

**Comment by alexcrichton** [comment]
Ok, I've pushed a commit which I believe addresses this. I've disabled it by default which mirrors the behavior of `tar` locally for me. Can you try it out and let me know if it works for you?

**Comment by b-ramsey** [comment]
While I can see that this would work when reading an archive (using the Archive reader object) when we are creating the archive from a filesystem (using the Builder writer object) it is still not possible to do so, unless there is a way to access this ArchiveInner property to associate it with the Builder that I am not currently seeing.

While it is true that while extracting (reading) a tar archive the permissions are not preserved by default; they are preserved by default while using tar in create mode (writing). i.e. tar -x vs tar -c.

In the case of this bug, the issue that I was seeing was from the create mode side of things.

**Comment by alexcrichton** [comment]
Oh oops, sorry about that! I think I missed the point... I believe in that case [this commit](https://github.com/alexcrichton/tar-rs/commit/470b6ab0670b3a3ca96808f368d728b7864241cd) would work, right?

**Comment by b-ramsey** [comment]
Yes this now works to preserve file permissions as the writer/builder. Thank you very much for implementing this fix.
